name: Secret redact testing

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  workflow-1:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Greeting message"
        run: echo "$Greeting $GITHUB_ACTOR. Secret is ${{ secrets.APP_SECRET }}"
      - name: "Write secret output"
        run: echo ${{ secrets.APP_SECRET }} > secret.txt
      - name: "View secret"
        run: cat secret.txt
        
