name: Secret redact testing

on:
  workflow_dispatch:
    inputs:
      APP_NAME:
        required: true
        type: string
    secrets:
      APP_SECRET:
        required: true

env:
  DAY_OF_WEEK: Monday

jobs:
  workflow-1:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    env:
      Greeting: Hello
    steps:
      - name: "Greeting message"
        run: echo "Secret is ${{ secrets.APP_SECRET }}"
        # run: echo "$Greeting $GITHUB_ACTOR. App name is: ${{ github.event.inputs.APP_NAME }}. Secret is ${{ secrets.APP_SECRET }}"
      - name: "Write secret output"
        run: echo ${{ secrets.APP_SECRET }} > secret.txt
      - name: "View secret"
        run: cat secret.txt
        
