name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  workflow-1:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Greeting message"
        run: echo "$Greeting $GITHUB_ACTOR. Secret is ${{ secrets.APP_SECRET }}"
        #env:
        #  First_Name: Mona
